Repository NYPL/discovery-front-end, pull requests merged in 2020-03, with the labels that each got.

#1189 SCC-1843
  src/app/components/SubjectHeading/AdditionalSubjectHeadingsButton.jsx
  src/app/components/SubjectHeading/NestedTableHeader.jsx
  src/app/components/SubjectHeading/SortButton.jsx
  src/app/components/SubjectHeading/SortMenu.jsx
  src/app/components/SubjectHeading/SubjectHeading.jsx
  src/app/components/SubjectHeading/SubjectHeadingsTableBody.jsx
  src/app/components/SubjectHeading/SubjectHeadingsTableHeader.jsx
  src/client/styles/components/SubjectHeadings.scss
  src/client/styles/components/SubjectHeadings/AdditionalSubjectHeadingsButton.scss
  src/client/styles/components/SubjectHeadings/NestedTableHeader.scss
  src/client/styles/components/SubjectHeadings/SubjectHeading.scss
  src/client/styles/components/SubjectHeadings/SubjectHeadingShow.scss
  src/client/styles/components/SubjectHeadings/SubjectHeadingsTable.scss
  src/client/styles/components/SubjectHeadings/SubjectHeadingsTableHeader.scss
Labels: changes made

#1196 SCC-1877 / fix search results breadcrumb bug
  src/app/components/Breadcrumbs/Breadcrumbs.jsx
  src/app/components/Results/ResultsList.jsx
  src/app/components/SubjectHeading/SubjectHeadingsTableBody.jsx
Labels: changes made

#1216 SCC-1889 - implement env variables for hold request using Store
  .env-sample
  README.md
  appConfig.js
  package-lock.json
  package.json
  server.js
  src/app/components/HoldRequest/HoldRequest.jsx
  src/app/components/HoldRequest/Notification.jsx
  src/app/components/Item/ItemTableRow.jsx
  src/app/stores/AppConfigStore.js
  test.env
Labels: WIP

#1214 Restyle links and buttons to match SCC;
  src/client/styles/components/SubjectHeadings/SubjectHeading.scss
Labels: post-merge review

#1213 Scc 1826
  src/app/components/SubjectHeading/SubjectHeadingShow.jsx
  src/app/components/SubjectHeading/SubjectHeadingsTableBody.jsx
  src/client/styles/components/SubjectHeadings/SubjectHeadingShow.scss
Labels: post-merge review

#1203 Scc 1846 text and styling
  src/app/components/SubjectHeading/AdditionalSubjectHeadingsButton.jsx
  src/app/components/SubjectHeading/SubjectHeading.jsx
  src/app/components/SubjectHeading/SubjectHeadingShow.jsx
  src/app/components/SubjectHeading/SubjectHeadingsTable.jsx
  src/app/components/SubjectHeading/SubjectHeadingsTableBody.jsx
  src/client/styles/components/SubjectHeadings.scss
  src/client/styles/components/SubjectHeadings/AdditionalSubjectHeadingsButton.scss
  src/client/styles/components/SubjectHeadings/SubjectHeadingShow.scss
Labels: post-merge review

#1236 change the behavior of `basicQuery()` to avoid fake "Search Results"
  src/app/utils/utils.js
  test/unit/utils.test.js
Labels: WIP
